name: test

on:
  push:
    branches:
        - 'feature/*'
        - 'main'
  workflow_dispatch:
    branches: ['*']

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [ Debug, Release, ReleaseTrace, ReleaseNoArch, ReleaseTraceNoArch ]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName
      with:
        tagRegex: |
          "^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
  
    - name: Create suffix param
      id: gensuffix
      shell: bash
      run: |
        [[ -n "${{ steps.tagName.outputs.prerelease }}" ]] && SUFFIX_PARAM="" || SUFFIX_PARAM="/p:vsuffix=${{ steps.tagName.outputs.prerelease }}"
        echo "vsuffix=${SUFFIX_PARAM}" >> "$GITHUB_OUTPUT"

    - name: Setup vcpkg for mwcapture
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'mwcapture/vcpkg.json'
        vcpkgConfigurationJsonGlob: 'mwcapture/vcpkg-configuration.json'
        
    - name: Setup vcpkg for mwcapture-test
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'mwcapture-test/vcpkg.json'      
        vcpkgConfigurationJsonGlob: 'mwcapture-test/vcpkg-configuration.json'

    - name: vcpkg integrate 
      run: vcpkg integrate install
      
    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild /t:Rebuild /p:Configuration=${{ matrix.configuration }} /p:vmajor=${{ steps.tagName.outputs.major }} /p:vminor=${{ steps.tagName.outputs.minor }} /p:vpatch=${{ steps.tagName.outputs.patch }} ${{ steps.gensuffix.outputs.vsuffix }}
